language: node_js
node_js:
  - "10"
  - "8"
install:
  - npm install
script:
  - npm test
  - npm run coverage
jobs:
  include:
    - stage: npm release
      if: branch = master
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_API_KEY
